version: '2'

services:
  app:
    image: 'metrics:latest'
    build:
      context: .
    container_name: metrics
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/metrics
      - SPRING_DATASOURCE_USERNAME=metrics
      - SPRING_DATASOURCE_PASSWORD=metrics
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=metrics
      - POSTGRES_PASSWORD=metrics
